/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package trains.of.sheffield;

public class App {
    // TODO: update price of pending/confirmed orders when a product is deleted

    /**
     * This is the main method which makes use of GUILoader.loginWindow() method.
     * @param args Unused.
     */
    public static void main(String[] args) {
        GUILoader.loginWindow(); // Loads the login window
    }
}
