/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package trains.of.sheffield;

public class App {
    // TODO: add JavaDocs to all classes
    // TODO: make all windows full screenY
    // TODO: remove unused main methods
    // TODO: check discussion board to see if locomotive, rolling stock, trackpacks in a trainset need to be separately modelled and how subtracting the stock works
    // TODO: Add test users - KRISH
    // TODO: Check blocker works
    // TODO: Copy signOut in MainMenu to other calls of MenuBarPanel
    // TODO: Fix Cascade delete - KRISH

    public static void main(String[] args) {
        GUILoader.loginWindow(); // Loads the login window
    }
}
