/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package trains.of.sheffield;

public class App {
    /**
     * This is the main method which makes use of GUILoader.loginWindow() method.
     */
    // TODO: add JavaDocs to all classes
    // TODO: alert on view basket when there isnt anything in the basket
    // TODO: alert when checking out a blocked order
    // TODO: Fix Cascade delete - KRISH
    // TODO: delete card details?
    // TODO: floating point error on total price in view orders
    // TODO: remove debug lines - GABES
    // TODO: a trainset can have multiple locomotives, rolling stock and trackpacks
    // TODO: Sort pending orders based on completion date
    // TODO: when adding a new product, check if product code is proper
    // TODO: show total price in order lines
    // TODO: cancel order from staff/customer
    // TODO: valid card in view orders
    public static void main(String[] args) {
        GUILoader.loginWindow(); // Loads the login window
    }
}
